### ISSUE TITLE
Library is not currently go gettable and tests are falsely passing.

### ISSUE THREAD

**Issue by bwghughes** [deferpanic/deferclient#22]
Hi,

Currently the library is not following convention, as as such a straight:

``` go get github.com/deferpanic/deferclient ``` won't work, however: ``` go get -d github.com/deferpanic/deferclient ``` works fine - as source is not built.

The packages should be in seperate repos as stated in:

https://github.com/golang/go/wiki/GithubCodeLayout

Also - it seems - possibly because of this - wercker is not running the tests.

If you'd like me to PR let me know.

Ben

**Comment by eyberg** [comment]
lol - nice catch @bwghughes - idk how that's been missed forever - fixed the builds with - https://github.com/deferpanic/deferclient/pull/23

as for go get - I'm not super against splitting up the repo but I think there's still some evolution at play here and is worth a bigger discussion on how that should look - two talking points from requests I've received in the past:

1) there are proposals to consolidate some of the higher level clients (deferlog/deferstats) into one - right now you effectively have to instatiate twice rather than once if you want both functionality

 &&

2) there are things like having more support for other databases and ORMs which might lend itself to the sep. repos you are proposing

**Comment by eyberg** [comment]
updating docs - 75ceebafb7c83ff26ba59672fd98b3836c673e7a - prob. will mv deferkv/deferlog out regardless
